cargo-features = ["edition2024"]

[package]
name = "hexagen"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs-next = "2.0.0"
lazy_static = "1.5.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
